'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LimeSeed.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_eject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_eject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_fs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_fs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_loop_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_loop_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_loop_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_loop_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_mute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_mute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_nomute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_nomute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c2_0j() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c2_0j", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c4_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c4_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c5_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c5_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c5_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c5_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c6_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c6_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c7_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c7_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chapters() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chapters", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property lame_enc_x64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lame_enc_x64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property lame_enc_x86() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("lame_enc_x86", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loadingart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadingart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loadingartlarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadingartlarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property norm() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("norm", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open_disc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_disc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_clr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_clr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_del() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_del", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_jump_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_jump_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_jump_previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_jump_previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_loop_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_loop_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_loop_hibernate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_loop_hibernate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_loop_restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_loop_restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_loop_shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_loop_shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_order() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_order", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_shuffle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_shuffle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_button_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_button_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property properties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("properties", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property q9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("q9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ratio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ratio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property side() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("side", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0 00 00 NO ADDITIONAL SENSE INFORMATION
        '''B 00 06 I/O PROCESS TERMINATED
        '''5 00 11 AUDIO PLAY OPERATION IN PROGRESS
        '''5 00 12 AUDIO PLAY OPERATION PAUSED
        '''5 00 13 AUDIO PLAY OPERATION SUCCESSFULLY COMPLETED
        '''5 00 14 AUDIO PLAY OPERATION STOPPED DUE TO ERROR
        '''5 00 15 NO CURRENT AUDIO STATUS TO RETURN
        '''4 00 17 CLEANING REQUESTED
        '''3 02 00 NO SEEK COMPLETE
        '''2 04 00 LOGICAL UNIT NOT READY, CAUSE NOT REPORTABLE
        '''2 04 01 LOGICAL UNIT IS IN PROCESS OF BECOMING READY
        '''2 04 02 LOGICAL UNIT NOT READY, INITIALIZING CMD. R [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property skascascq() As String
            Get
                Return ResourceManager.GetString("skascascq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property subtitles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("subtitles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property throbber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("throbber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_pause0() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_pause0", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_pause1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_pause1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_play0() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_play0", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_play1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_play1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_play2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_play2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_play3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_play3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_play4() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_play4", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_play5() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_play5", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_play6() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_play6", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_play7() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_play7", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tray_stop() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tray_stop", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_ff() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_ff", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_ff_disabled() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_ff_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_ff_hover() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_ff_hover", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_pause() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_pause", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_pause_disabled() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_pause_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_pause_hover() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_pause_hover", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_play() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_play", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_play_disabled() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_play_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_play_hover() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_play_hover", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_restore() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_restore", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_restore_hover() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_restore_hover", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_rw() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_rw", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_rw_disabled() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_rw_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_rw_hover() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_rw_hover", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_stop() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_stop", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_stop_disabled() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_stop_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property traybutton_stop_hover() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("traybutton_stop_hover", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tt_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tt_copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tt_link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tt_link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tt_move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tt_move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnknownAlbum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnknownAlbum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property visualization() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("visualization", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
