'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("640, 480")>  _
        Public Property Size() As Global.System.Drawing.Size
            Get
                Return CType(Me("Size"),Global.System.Drawing.Size)
            End Get
            Set
                Me("Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.11")>  _
        Public Property Gapless() As Double
            Get
                Return CType(Me("Gapless"),Double)
            End Get
            Set
                Me("Gapless") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MustUpgrade() As Boolean
            Get
                Return CType(Me("MustUpgrade"),Boolean)
            End Get
            Set
                Me("MustUpgrade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SingleInstance() As Boolean
            Get
                Return CType(Me("SingleInstance"),Boolean)
            End Get
            Set
                Me("SingleInstance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Device() As String
            Get
                Return CType(Me("Device"),String)
            End Get
            Set
                Me("Device") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl + F1")>  _
        Public Property Keyboard_About() As String
            Get
                Return CType(Me("Keyboard_About"),String)
            End Get
            Set
                Me("Keyboard_About") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Insert")>  _
        Public Property Keyboard_AddToPL() As String
            Get
                Return CType(Me("Keyboard_AddToPL"),String)
            End Get
            Set
                Me("Keyboard_AddToPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Shift + Delete")>  _
        Public Property Keyboard_ClearPL() As String
            Get
                Return CType(Me("Keyboard_ClearPL"),String)
            End Get
            Set
                Me("Keyboard_ClearPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl + C")>  _
        Public Property Keyboard_Close() As String
            Get
                Return CType(Me("Keyboard_Close"),String)
            End Get
            Set
                Me("Keyboard_Close") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Shift + Enter")>  _
        Public Property Keyboard_FS() As String
            Get
                Return CType(Me("Keyboard_FS"),String)
            End Get
            Set
                Me("Keyboard_FS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Home")>  _
        Public Property Keyboard_Last() As String
            Get
                Return CType(Me("Keyboard_Last"),String)
            End Get
            Set
                Me("Keyboard_Last") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl + M")>  _
        Public Property Keyboard_Mute() As String
            Get
                Return CType(Me("Keyboard_Mute"),String)
            End Get
            Set
                Me("Keyboard_Mute") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("End")>  _
        Public Property Keyboard_Next() As String
            Get
                Return CType(Me("Keyboard_Next"),String)
            End Get
            Set
                Me("Keyboard_Next") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl + O")>  _
        Public Property Keyboard_Open() As String
            Get
                Return CType(Me("Keyboard_Open"),String)
            End Get
            Set
                Me("Keyboard_Open") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Keyboard_OpenPL() As String
            Get
                Return CType(Me("Keyboard_OpenPL"),String)
            End Get
            Set
                Me("Keyboard_OpenPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Spacebar")>  _
        Public Property Keyboard_PlayPause() As String
            Get
                Return CType(Me("Keyboard_PlayPause"),String)
            End Get
            Set
                Me("Keyboard_PlayPause") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl + P")>  _
        Public Property Keyboard_Props() As String
            Get
                Return CType(Me("Keyboard_Props"),String)
            End Get
            Set
                Me("Keyboard_Props") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Delete")>  _
        Public Property Keyboard_RemoveFromPL() As String
            Get
                Return CType(Me("Keyboard_RemoveFromPL"),String)
            End Get
            Set
                Me("Keyboard_RemoveFromPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl + F2")>  _
        Public Property Keyboard_RenamePL() As String
            Get
                Return CType(Me("Keyboard_RenamePL"),String)
            End Get
            Set
                Me("Keyboard_RenamePL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Keyboard_RepeatPL() As String
            Get
                Return CType(Me("Keyboard_RepeatPL"),String)
            End Get
            Set
                Me("Keyboard_RepeatPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Keyboard_RepeatTrack() As String
            Get
                Return CType(Me("Keyboard_RepeatTrack"),String)
            End Get
            Set
                Me("Keyboard_RepeatTrack") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Keyboard_SavePL() As String
            Get
                Return CType(Me("Keyboard_SavePL"),String)
            End Get
            Set
                Me("Keyboard_SavePL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl + S")>  _
        Public Property Keyboard_Settings() As String
            Get
                Return CType(Me("Keyboard_Settings"),String)
            End Get
            Set
                Me("Keyboard_Settings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Keyboard_Shuffle() As String
            Get
                Return CType(Me("Keyboard_Shuffle"),String)
            End Get
            Set
                Me("Keyboard_Shuffle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Left Arrow")>  _
        Public Property Keyboard_SkipBack() As String
            Get
                Return CType(Me("Keyboard_SkipBack"),String)
            End Get
            Set
                Me("Keyboard_SkipBack") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Right Arrow")>  _
        Public Property Keyboard_SkipFwd() As String
            Get
                Return CType(Me("Keyboard_SkipFwd"),String)
            End Get
            Set
                Me("Keyboard_SkipFwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Escape")>  _
        Public Property Keyboard_Stop() As String
            Get
                Return CType(Me("Keyboard_Stop"),String)
            End Get
            Set
                Me("Keyboard_Stop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Page Down")>  _
        Public Property Keyboard_VolDown() As String
            Get
                Return CType(Me("Keyboard_VolDown"),String)
            End Get
            Set
                Me("Keyboard_VolDown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Page Up")>  _
        Public Property Keyboard_VolUp() As String
            Get
                Return CType(Me("Keyboard_VolUp"),String)
            End Get
            Set
                Me("Keyboard_VolUp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ctrl + W")>  _
        Public Property Keyboard_Webpage() As String
            Get
                Return CType(Me("Keyboard_Webpage"),String)
            End Get
            Set
                Me("Keyboard_Webpage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_About() As String
            Get
                Return CType(Me("Gamepad_About"),String)
            End Get
            Set
                Me("Gamepad_About") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_AddToPL() As String
            Get
                Return CType(Me("Gamepad_AddToPL"),String)
            End Get
            Set
                Me("Gamepad_AddToPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_ClearPL() As String
            Get
                Return CType(Me("Gamepad_ClearPL"),String)
            End Get
            Set
                Me("Gamepad_ClearPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_Close() As String
            Get
                Return CType(Me("Gamepad_Close"),String)
            End Get
            Set
                Me("Gamepad_Close") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Button 1")>  _
        Public Property Gamepad_FS() As String
            Get
                Return CType(Me("Gamepad_FS"),String)
            End Get
            Set
                Me("Gamepad_FS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Button 5")>  _
        Public Property Gamepad_Last() As String
            Get
                Return CType(Me("Gamepad_Last"),String)
            End Get
            Set
                Me("Gamepad_Last") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Button 3")>  _
        Public Property Gamepad_Mute() As String
            Get
                Return CType(Me("Gamepad_Mute"),String)
            End Get
            Set
                Me("Gamepad_Mute") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Button 6")>  _
        Public Property Gamepad_Next() As String
            Get
                Return CType(Me("Gamepad_Next"),String)
            End Get
            Set
                Me("Gamepad_Next") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Button 10")>  _
        Public Property Gamepad_Open() As String
            Get
                Return CType(Me("Gamepad_Open"),String)
            End Get
            Set
                Me("Gamepad_Open") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_OpenPL() As String
            Get
                Return CType(Me("Gamepad_OpenPL"),String)
            End Get
            Set
                Me("Gamepad_OpenPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Button 2")>  _
        Public Property Gamepad_PlayPause() As String
            Get
                Return CType(Me("Gamepad_PlayPause"),String)
            End Get
            Set
                Me("Gamepad_PlayPause") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_Props() As String
            Get
                Return CType(Me("Gamepad_Props"),String)
            End Get
            Set
                Me("Gamepad_Props") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_RemoveFromPL() As String
            Get
                Return CType(Me("Gamepad_RemoveFromPL"),String)
            End Get
            Set
                Me("Gamepad_RemoveFromPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_RenamePL() As String
            Get
                Return CType(Me("Gamepad_RenamePL"),String)
            End Get
            Set
                Me("Gamepad_RenamePL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_RepeatPL() As String
            Get
                Return CType(Me("Gamepad_RepeatPL"),String)
            End Get
            Set
                Me("Gamepad_RepeatPL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_RepeatTrack() As String
            Get
                Return CType(Me("Gamepad_RepeatTrack"),String)
            End Get
            Set
                Me("Gamepad_RepeatTrack") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_SavePL() As String
            Get
                Return CType(Me("Gamepad_SavePL"),String)
            End Get
            Set
                Me("Gamepad_SavePL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_Settings() As String
            Get
                Return CType(Me("Gamepad_Settings"),String)
            End Get
            Set
                Me("Gamepad_Settings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_Shuffle() As String
            Get
                Return CType(Me("Gamepad_Shuffle"),String)
            End Get
            Set
                Me("Gamepad_Shuffle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("X Axis Left")>  _
        Public Property Gamepad_SkipBack() As String
            Get
                Return CType(Me("Gamepad_SkipBack"),String)
            End Get
            Set
                Me("Gamepad_SkipBack") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("X Axis Right")>  _
        Public Property Gamepad_SkipFwd() As String
            Get
                Return CType(Me("Gamepad_SkipFwd"),String)
            End Get
            Set
                Me("Gamepad_SkipFwd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Button 4")>  _
        Public Property Gamepad_Stop() As String
            Get
                Return CType(Me("Gamepad_Stop"),String)
            End Get
            Set
                Me("Gamepad_Stop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Y Axis Bottom")>  _
        Public Property Gamepad_VolDown() As String
            Get
                Return CType(Me("Gamepad_VolDown"),String)
            End Get
            Set
                Me("Gamepad_VolDown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Y Axis Top")>  _
        Public Property Gamepad_VolUp() As String
            Get
                Return CType(Me("Gamepad_VolUp"),String)
            End Get
            Set
                Me("Gamepad_VolUp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_Webpage() As String
            Get
                Return CType(Me("Gamepad_Webpage"),String)
            End Get
            Set
                Me("Gamepad_Webpage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Alt + Spacebar")>  _
        Public Property Keyboard_DVDMenu() As String
            Get
                Return CType(Me("Keyboard_DVDMenu"),String)
            End Get
            Set
                Me("Keyboard_DVDMenu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Down Arrow")>  _
        Public Property Keyboard_DiscEject() As String
            Get
                Return CType(Me("Keyboard_DiscEject"),String)
            End Get
            Set
                Me("Keyboard_DiscEject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Button 9")>  _
        Public Property Gamepad_DVDMenu() As String
            Get
                Return CType(Me("Gamepad_DVDMenu"),String)
            End Get
            Set
                Me("Gamepad_DVDMenu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Gamepad_DiscEject() As String
            Get
                Return CType(Me("Gamepad_DiscEject"),String)
            End Get
            Set
                Me("Gamepad_DiscEject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property Visualization() As String
            Get
                Return CType(Me("Visualization"),String)
            End Get
            Set
                Me("Visualization") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Keyboard() As Boolean
            Get
                Return CType(Me("Keyboard"),Boolean)
            End Get
            Set
                Me("Keyboard") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Gamepad() As Boolean
            Get
                Return CType(Me("Gamepad"),Boolean)
            End Get
            Set
                Me("Gamepad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property BeatBG() As Boolean
            Get
                Return CType(Me("BeatBG"),Boolean)
            End Get
            Set
                Me("BeatBG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property Visualization_Rate() As Integer
            Get
                Return CType(Me("Visualization_Rate"),Integer)
            End Get
            Set
                Me("Visualization_Rate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultLocale() As String
            Get
                Return CType(Me("DefaultLocale"),String)
            End Get
            Set
                Me("DefaultLocale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Subtitles() As Boolean
            Get
                Return CType(Me("Subtitles"),Boolean)
            End Get
            Set
                Me("Subtitles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Topmost() As Boolean
            Get
                Return CType(Me("Topmost"),Boolean)
            End Get
            Set
                Me("Topmost") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LimeSeed.My.MySettings
            Get
                Return Global.LimeSeed.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
